title: Inquisit0r67
email: siddharthjani@hotmail.com
baseurl: "" 
url: "https://Inquisit0r67.github.io" 
github_username:  Inquisit0r67
repository: Inquisit0r67/Inquisit0r67.github.io
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

